### ISSUE TITLE
Module connection

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/SOLARMINI01#3]
Vzhledem ke způsobům využití modulu se ukázalo jako ne úplně praktické mít wago svorkovnici i na výstupu. Na základě výkonových možností, které modul má bych zde navrhoval spíše využít klasický MLAB hřebínek 2x3 piny.  Wago svorkovnice na vstupní straně je naopak užitečná, neboť je zde nutné připojit solární panel, který v předpokládaných rozměrech typicky končí volnými vodiči. Spojení panelu a vstupu měniče navíc musí mít dobrou elektrickou vodivost kvůli nízkým napětím a relativně vysokým proudům na této straně.

**Comment by ChroustJan** [comment]
Verze 01B nahrazuje WAGO hřebínkem 2x3 piny.
