### ISSUE TITLE
divider for LTO cells

### ISSUE THREAD

**Issue by kakl** [mlab-modules/SOLARMINI01#8]
delic v solarmini je 100:110 k ohm
dava to 2,69 V az 2,77 V naprazdno pri 1 % odporech
R7 = 110 k
R8 = 100 k

**Comment by kakl** [comment]
R7 = 100 k
R8 = 91 k
dava 2,76 V, to je jeste lepsi

**Comment by kaklik** [comment]
Je to aplikováno v [návrhu nového modulu pro LTO články](https://github.com/mlab-modules/SOLARMINIBAT01).
